### ISSUE TITLE
Do you want to make a pull request to vis.js?

### ISSUE THREAD

**Issue by ooker777** [justinharrell/vis-svg#2]
I come across your script from [Issue #841 · visjs/vis-network](https://github.com/visjs/vis-network/issues/841 "SVG (PNG, JPEG) ... picture format export support? · Issue #841 · visjs/vis-network"). I wonder if you have thought about making a pull request into that project?

**Comment by justinharrell** [comment]
Back when I was active in vis.js development there was resistance to incorporate these changes, looks like that hasn't changed.

This is pretty easy to implement though as it just reaches in and replaces the canvas context temporarily for one redraw. It has worked well for us, canvas2svg is mostly complete I haven't seen anything vis.js does that it can't handle, I just made some changes to it to support embedding images.

Anyone is free to use this and perhaps incorporate into vis.js.

**Comment by jstitlow** [comment]
Hah! I just used this today and am very appreciative of the effort. +1000 up-votes for pulling into vis-network!!! Have tested several network diagram workflows for generating publication/presentation visualizations over the last couple weeks and vis.js (via the pyvis wrapper) is superb. 

I don't have the .js chops to incorporate this into vis.js but could add the 'export .svg' button to pyvis.
